---

x-condition-healthy: &healthy
  condition: service_healthy

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

services:
  test:
    build: .
    environment:
      MARIADB_HATHIFILES_RW_USERNAME: "ht_rights"
      MARIADB_HATHIFILES_RW_PASSWORD: "ht_rights"
      MARIADB_HATHIFILES_RW_HOST: "mariadb"
      MARIADB_HATHIFILES_RW_DATABASE: "ht"
      HATHIFILES_DIR: "/usr/src/app/spec/data"
      PUSHGATEWAY: http://pushgateway:9091
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: bundle exec rspec
    depends_on:
      mariadb: *healthy

  mariadb:
    image: mariadb:latest
    #volumes:
    #  - ./sql/100_rights_log.sql:/docker-entrypoint-initdb.d/100_rights_log.sql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ht
      MYSQL_USER: ht_rights
      MYSQL_PASSWORD: ht_rights
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9092:9091
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "wget", "--quiet", "--tries=1", "-O", "/dev/null", "pushgateway:9091/-/healthy" ]

volumes:
  gem_cache:

