#!/usr/bin/env ruby

# This is the preferred, date-independent way of bringing the database
# completely up to date with the hathifiles inventory using the hathifiles.hf_log
# database table.

$LOAD_PATH.unshift "../lib"

require "dotenv"
require "pathname"
require "push_metrics"
require "tmpdir"

require "hathifiles_database"

envfile = Pathname.new(__dir__).parent + ".env"
Dotenv.load(envfile)

connection = HathifilesDatabase.new(ENV["HATHIFILES_MYSQL_CONNECTION"])
hathifiles = HathifilesDatabase::Hathifiles.new(
  hathifiles_directory: ENV["HATHIFILES_DIR"],
  connection: connection
)

tracker = PushMetrics.new(
  batch_size: 10,
  job_name: "hathifiles_database",
  logger: connection.logger
)

Dir.mktmpdir do |tempdir|
  connection.logger.info "full hathifiles: #{hathifiles.missing_full_hathifiles}"
  hathifiles.missing_full_hathifiles.each do |hathifile|
    hathifile = File.join(ENV["HATHIFILES_DIR"], hathifile)
    connection.logger.info "processing monthly #{hathifile}"
    HathifilesDatabase::MonthlyUpdate.new(
      connection: connection,
      hathifile: hathifile,
      output_directory: tempdir
    ).run do
      tracker.increment_and_log_batch_line
    end
  end
  connection.logger.info "updates: #{hathifiles.missing_update_hathifiles}"
  hathifiles.missing_update_hathifiles.each do |hathifile|
    hathifile = File.join(ENV["HATHIFILES_DIR"], hathifile)
    connection.logger.info "processing update #{hathifile}"
    connection.update_from_file(hathifile) do
      tracker.increment_and_log_batch_line
    end
  end
end
tracker.log_final_line
