#!/usr/bin/env ruby

$:.unshift "../lib"

require "dotenv"
require "hathifiles_database"
require "pathname"
require "tmpdir"

envfile = Pathname.new(__dir__).parent + ".env"
Dotenv.load(envfile)

# Use the monthly hathifile from command line
hathifile = ARGV[0]
# Fall back to the most recent daily hathifile if not specified
if hathifile.nil?
  hathifile = Dir.glob(File.join(ENV["HATHIFILES_DIR"], "hathi_upd*")).max
end

connection = HathifilesDatabase.new(ENV["HATHIFILES_MYSQL_CONNECTION"])

# Do all operations in temporary directory so intermediate files get cleaned up
Dir.mktmpdir do |tempdir|
  connection.logger.info "Starting work on #{hathifile}"
  connection.update_from_file hathifile
end
