#!/usr/bin/env ruby

require "date_named_file"
require "hathifiles_database"
require "dotenv"

HF_FILES = "/htapps/archive/hathifiles"
LOGFILE_DIR = "../logs/hathifiles_database"

envfile = Pathname.new(__dir__).parent + ".env"
# devenvfile = Pathname.new(__dir__).parent + ".devenv"

Dotenv.load(envfile)
connection_string = ENV["HATHIFILES_MYSQL_CONNECTION"]
connection = HathifilesDatabase.new(connection_string)

production = connection.rawdb

Dotenv.load(envfile)
connection_string = ENV["HATHIFILES_MYSQL_CONNECTION"]
reindex_connection = HathifilesDatabase.new(connection_string)

reindex = reindex_connection.rawdb

def prod(t)
  "hathifiles.#{t}"
end

def tmp(t)
  "hathifiles.#{t}_swap"
end

def ri(t)
  "hathifiles_reindex.#{t}"
end

# Get tables that are in both
tables = production.tables.intersection(reindex.tables)

renames = tables.flat_map { |t| [[prod(t), tmp(t)], [ri(t), prod(t)], [tmp(t), ri(t)]] }
sql = "RENAME TABLE " + renames.map { |x| x.join(" TO ") }.join(", ")

production.run(sql)
