name: Build latest from main and deploy to staging

on:
  workflow_run:
    workflows: [ 'Run Tests']
    branches: [ 'main' ]
    types: [ completed ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: hathitrust/github_actions/build@v1
        with:
          image: ghcr.io/${{ github.repository }}-unstable
          dockerfile: Dockerfile.prod
          tag: ${{ github.sha }}
          push_latest: true
          registry_token: ${{ github.token }}

  # Enable this part if there is a staging environment that
  # you wish to automatically deploy to when merging to main
  # deploy-staging:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: staging
  #   steps:
  #   - name: Deploy to staging
  #     uses: mlibrary/deploy-to-kubernetes@v3
  #     with:
  #       registry_token: ${{ github.token }}
  #       image: ghcr.io/${{ github.repository }}-unstable:${{ github.sha }}
  #       cluster_ca: ${{ secrets.KUBERNETES_CA }}
  #       cluster_server: ${{ secrets.KUBERNETES_SERVER }}
  #       namespace_token: ${{ secrets.KUBERNETES_TOKEN }}
  #       namespace: ${{ secrets.KUBERNETES_NAMESPACE }}
